import Head from 'next/head';
import getSearch from '../services/getSearch';
import getAccesToken from '../services/getAccesToken';
import AppLayout from '../components/AppLayout';
import MainSection from '../components/MainSection';
import MainSectionLayout from '../components/MainSectionLayout';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';

import styles from '../styles/Home.module.css';

export default function Home({ access_token, token_type }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotify-logo.ico" />
      </Head>

      <AppLayout>
        <Sidebar />
        <MainSectionLayout>
          <Navbar />
          <MainSection />
        </MainSectionLayout>
        <main />
      </AppLayout>
    </div>
  );
}

// export async function getStaticProps() {
//   const fs = require('fs');
//   const credentials = await getAccesToken();
//   fs.writeFileSync(
//     './cache/cache_credentials.json',
//     JSON.stringify(credentials)
//   );

//   return {
//     props: credentials,
//   };
// }
